# Use Python 3.10 slim image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /code

# Copy the requirements file and install dependencies
COPY ./encoderAPI/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Copy the rest of the application code
COPY ./encoderAPI /code/encoderAPI

# Command to run the FastAPI app
CMD ["uvicorn", "encoderAPI.main:app", "--host", "0.0.0.0", "--port", "8000"]
