apiVersion: apps/v1
kind: Deployment
metadata:
  name: encoder-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encoder-api
  template:
    metadata:
      labels:
        app: encoder-api
    spec:
      containers:
      - name: encoder-api
        image: mchianale/encoder-api:latest
        ports:
        - containerPort: 8000
     
---
apiVersion: v1
kind: Service
metadata:
  name: encoder-api
spec:
  selector:
    app: encoder-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP